version: '3'
services:
  hasura:
    image: hasura/graphql-engine:v1.2.0-beta.3.cli-migrations
    ports:
      - "8101:8080"
    restart: always
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_SECRET:-MY_SUPER_HASURA_SECRET}
    volumes:
      - ./backend-ng/hasura/migrations:/hasura-migrations

  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  create_message:
    build:
      context: "./backend-ng/api/create-message"
      dockerfile: ${DOCKERFILE:-Dockerfile}
    environment:
      HASURA_SECRET: ${HASURA_SECRET:-MY_SUPER_HASURA_SECRET}
    volumes:
      - "./backend-ng/api/create-message:/go/src/lambda"
    depends_on:
      - "hasura"


volumes:
  db_data:
